'use client'
import { useState } from 'react'
import Header from '../../components/Header'
import Footer from '../../components/Footer'
import { Shield, Users, Database, Settings, Lock, Eye, Download, Share2, CheckCircle, AlertTriangle } from 'lucide-react'

export default function DataProtection() {
  const [activeTab, setActiveTab] = useState('community-ownership')

  const protectionFeatures = [
    {
      id: 'community-ownership',
      title: 'Community Ownership',
      icon: Users,
      description: 'All data belongs to the community',
      color: 'green'
    },
    {
      id: 'privacy-controls',
      title: 'Privacy Controls',
      icon: Eye,
      description: 'Choose what to share and with whom',
      color: 'blue'
    },
    {
      id: 'local-storage',
      title: 'Local Storage',
      icon: Database,
      description: 'Important information stored locally, not just in the cloud',
      color: 'purple'
    },
    {
      id: 'simple-permissions',
      title: 'Simple Permissions',
      icon: Settings,
      description: 'Easy controls for who can access what information',
      color: 'orange'
    }
  ]

  const dataTypes = [
    {
      name: 'Traditional Knowledge',
      description: 'Elder teachings, cultural practices, traditional medicine',
      sensitivity: 'High',
      ownership: 'Community',
      sharing: 'Restricted',
      storage: 'Local + Encrypted Cloud'
    },
    {
      name: 'Environmental Data',
      description: 'Weather observations, forest health, wildlife sightings',
      sensitivity: 'Medium',
      ownership: 'Community',
      sharing: 'Selective',
      storage: 'Local + Cloud'
    },
    {
      name: 'Community Projects',
      description: 'Conservation initiatives, success stories, progress reports',
      sensitivity: 'Low',
      ownership: 'Community',
      sharing: 'Public',
      storage: 'Cloud'
    },
    {
      name: 'Personal Information',
      description: 'User profiles, contact details, participation records',
      sensitivity: 'High',
      ownership: 'Individual',
      sharing: 'Private',
      storage: 'Local + Encrypted'
    }
  ]

  const permissionLevels = [
    {
      level: 'Community Members',
      access: ['View public knowledge', 'Submit observations', 'Participate in discussions'],
      restrictions: ['Cannot access sensitive traditional knowledge', 'Cannot modify community decisions']
    },
    {
      level: 'Community Leaders',
      access: ['Manage community data', 'Control sharing permissions', 'Access all community knowledge'],
      restrictions: ['Cannot share without community consent', 'Cannot delete traditional knowledge']
    },
    {
      level: 'External Partners',
      access: ['View approved public data', 'Submit funding proposals', 'Receive progress reports'],
      restrictions: ['No access to sensitive knowledge', 'Cannot modify community data', 'Must follow traditional protocols']
    },
    {
      level: 'Researchers',
      access: ['Access approved research data', 'Submit research proposals', 'Collaborate on studies'],
      restrictions: ['Require community approval', 'Must share research results', 'Cannot commercialize without consent']
    }
  ]

  const getColorClasses = (color) => {
    const colors = {
      green: 'bg-green-100 text-green-600 border-green-200',
      blue: 'bg-blue-100 text-blue-600 border-blue-200',
      purple: 'bg-purple-100 text-purple-600 border-purple-200',
      orange: 'bg-orange-100 text-orange-600 border-orange-200'
    }
    return colors[color] || 'bg-gray-100 text-gray-600 border-gray-200'
  }

  const getSensitivityColor = (sensitivity) => {
    switch(sensitivity) {
      case 'High': return 'bg-red-100 text-red-700'
      case 'Medium': return 'bg-yellow-100 text-yellow-700'
      case 'Low': return 'bg-green-100 text-green-700'
      default: return 'bg-gray-100 text-gray-700'
    }
  }

  const renderContent = () => {
    switch(activeTab) {
      case 'community-ownership':
        return (
          <div className="space-y-6">
            <h3 className="text-2xl font-bold text-gray-900 mb-6">Community Data Ownership</h3>
            
            <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-8">
              <div className="flex items-center mb-4">
                <Users className="w-6 h-6 text-green-600 mr-3" />
                <h4 className="text-lg font-semibold text-green-900">Core Principle</h4>
              </div>
              <p className="text-green-800">
                All data generated by and about your community belongs to your community. 
                You have complete control over how it's used, shared, and protected.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
                <h5 className="text-lg font-semibold text-gray-900 mb-4">What This Means</h5>
                <ul className="space-y-3">
                  <li className="flex items-start">
                    <CheckCircle className="w-5 h-5 text-green-500 mr-3 mt-0.5" />
                    <span className="text-gray-600">Your community decides who can access your data</span>
                  </li>
                  <li className="flex items-start">
                    <CheckCircle className="w-5 h-5 text-green-500 mr-3 mt-0.5" />
                    <span className="text-gray-600">You can revoke access at any time</span>
                  </li>
                  <li className="flex items-start">
                    <CheckCircle className="w-5 h-5 text-green-500 mr-3 mt-0.5" />
                    <span className="text-gray-600">No data is shared without your explicit consent</span>
                  </li>
                  <li className="flex items-start">
                    <CheckCircle className="w-5 h-5 text-green-500 mr-3 mt-0.5" />
                    <span className="text-gray-600">You receive benefits from any commercial use</span>
                  </li>
                </ul>
              </div>

              <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
                <h5 className="text-lg font-semibold text-gray-900 mb-4">Legal Protections</h5>
                <ul className="space-y-3">
                  <li className="flex items-start">
                    <Shield className="w-5 h-5 text-blue-500 mr-3 mt-0.5" />
                    <span className="text-gray-600">Complies with international indigenous rights laws</span>
                  </li>
                  <li className="flex items-start">
                    <Shield className="w-5 h-5 text-blue-500 mr-3 mt-0.5" />
                    <span className="text-gray-600">Follows traditional governance protocols</span>
                  </li>
                  <li className="flex items-start">
                    <Shield className="w-5 h-5 text-blue-500 mr-3 mt-0.5" />
                    <span className="text-gray-600">Encrypted storage and transmission</span>
                  </li>
                  <li className="flex items-start">
                    <Shield className="w-5 h-5 text-blue-500 mr-3 mt-0.5" />
                    <span className="text-gray-600">Regular security audits and updates</span>
                  </li>
                </ul>
              </div>
            </div>

            <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
              <h5 className="text-lg font-semibold text-gray-900 mb-4">Data Types and Ownership</h5>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-gray-200">
                      <th className="text-left py-3 px-4 font-medium text-gray-700">Data Type</th>
                      <th className="text-left py-3 px-4 font-medium text-gray-700">Sensitivity</th>
                      <th className="text-left py-3 px-4 font-medium text-gray-700">Ownership</th>
                      <th className="text-left py-3 px-4 font-medium text-gray-700">Default Sharing</th>
                    </tr>
                  </thead>
                  <tbody>
                    {dataTypes.map((data, index) => (
                      <tr key={index} className="border-b border-gray-100">
                        <td className="py-3 px-4">
                          <div>
                            <div className="font-medium text-gray-900">{data.name}</div>
                            <div className="text-sm text-gray-500">{data.description}</div>
                          </div>
                        </td>
                        <td className="py-3 px-4">
                          <span className={`px-2 py-1 rounded-full text-xs font-medium ${getSensitivityColor(data.sensitivity)}`}>
                            {data.sensitivity}
                          </span>
                        </td>
                        <td className="py-3 px-4 text-gray-600">{data.ownership}</td>
                        <td className="py-3 px-4 text-gray-600">{data.sharing}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )

      case 'privacy-controls':
        return (
          <div className="space-y-6">
            <h3 className="text-2xl font-bold text-gray-900 mb-6">Privacy Controls</h3>
            
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-8">
              <div className="flex items-center mb-4">
                <Eye className="w-6 h-6 text-blue-600 mr-3" />
                <h4 className="text-lg font-semibold text-blue-900">Granular Control</h4>
              </div>
              <p className="text-blue-800">
                Choose exactly what information to share, with whom, and under what conditions. 
                Your privacy settings can be as simple or detailed as you need.
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
                <h5 className="text-lg font-semibold text-gray-900 mb-4">Sharing Options</h5>
                <div className="space-y-4">
                  <div className="border border-gray-200 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="font-medium text-gray-900">Traditional Knowledge</span>
                      <button className="text-blue-600 text-sm">Edit</button>
                    </div>
                    <div className="text-sm text-gray-600 mb-2">Shared with: Community Members Only</div>
                    <div className="flex items-center">
                      <Lock className="w-4 h-4 text-red-500 mr-2" />
                      <span className="text-sm text-red-600">Restricted Access</span>
                    </div>
                  </div>

                  <div className="border border-gray-200 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="font-medium text-gray-900">Environmental Data</span>
                      <button className="text-blue-600 text-sm">Edit</button>
                    </div>
                    <div className="text-sm text-gray-600 mb-2">Shared with: Approved Researchers</div>
                    <div className="flex items-center">
                      <Eye className="w-4 h-4 text-yellow-500 mr-2" />
                      <span className="text-sm text-yellow-600">Selective Sharing</span>
                    </div>
                  </div>

                  <div className="border border-gray-200 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="font-medium text-gray-900">Success Stories</span>
                      <button className="text-blue-600 text-sm">Edit</button>
                    </div>
                    <div className="text-sm text-gray-600 mb-2">Shared with: Public</div>
                    <div className="flex items-center">
                      <Share2 className="w-4 h-4 text-green-500 mr-2" />
                      <span className="text-sm text-green-600">Public Access</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
                <h5 className="text-lg font-semibold text-gray-900 mb-4">Access Requests</h5>
                <div className="space-y-4">
                  <div className="border border-orange-200 bg-orange-50 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="font-medium text-gray-900">University Research Team</span>
                      <span className="text-xs bg-orange-100 text-orange-700 px-2 py-1 rounded">Pending</span>
                    </div>
                    <div className="text-sm text-gray-600 mb-3">
                      Requesting access to biodiversity data for climate change study
                    </div>
                    <div className="flex space-x-2">
                      <button className="bg-green-600 text-white px-3 py-1 rounded text-sm">Approve</button>
                      <button className="bg-red-600 text-white px-3 py-1 rounded text-sm">Deny</button>
                      <button className="bg-gray-600 text-white px-3 py-1 rounded text-sm">Details</button>
                    </div>
                  </div>

                  <div className="border border-green-200 bg-green-50 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="font-medium text-gray-900">Conservation NGO</span>
                      <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded">Approved</span>
                    </div>
                    <div className="text-sm text-gray-600 mb-3">
                      Access granted to forest monitoring data for funding proposal
                    </div>
                    <div className="text-xs text-gray-500">Approved 2 days ago • Expires in 6 months</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )

      case 'local-storage':
        return (
          <div className="space-y-6">
            <h3 className="text-2xl font-bold text-gray-900 mb-6">Local Storage & Data Security</h3>
            
            <div className="bg-purple-50 border border-purple-200 rounded-lg p-6 mb-8">
              <div className="flex items-center mb-4">
                <Database className="w-6 h-6 text-purple-600 mr-3" />
                <h4 className="text-lg font-semibold text-purple-900">Hybrid Storage Approach</h4>
              </div>
              <p className="text-purple-800">
                Critical data is stored locally on community devices, with encrypted backups in the cloud. 
                This ensures access even without internet connection and protects against data loss.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              <div className="bg-white rounded-lg p-6 text-center shadow-sm border border-gray-100">
                <Database className="w-12 h-12 text-purple-600 mx-auto mb-4" />
                <h5 className="font-semibold text-gray-900 mb-2">Local Storage</h5>
                <p className="text-sm text-gray-600">Essential data stored on community devices for offline access</p>
              </div>
              <div className="bg-white rounded-lg p-6 text-center shadow-sm border border-gray-100">
                <Shield className="w-12 h-12 text-blue-600 mx-auto mb-4" />
                <h5 className="font-semibold text-gray-900 mb-2">Encrypted Backup</h5>
                <p className="text-sm text-gray-600">Secure cloud backup with military-grade encryption</p>
              </div>
              <div className="bg-white rounded-lg p-6 text-center shadow-sm border border-gray-100">
                <Download className="w-12 h-12 text-green-600 mx-auto mb-4" />
                <h5 className="font-semibold text-gray-900 mb-2">Data Export</h5>
                <p className="text-sm text-gray-600">Download your data anytime in standard formats</p>
              </div>
            </div>

            <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
              <h5 className="text-lg font-semibold text-gray-900 mb-4">Storage Locations by Data Type</h5>
              <div className="space-y-4">
                {dataTypes.map((data, index) => (
                  <div key={index} className="flex items-center justify-between p-4 border border-gray-200 rounded-lg">
                    <div>
                      <div className="font-medium text-gray-900">{data.name}</div>
                      <div className="text-sm text-gray-500">{data.description}</div>
                    </div>
                    <div className="text-right">
                      <div className="text-sm font-medium text-gray-700">{data.storage}</div>
                      <div className={`text-xs px-2 py-1 rounded-full ${getSensitivityColor(data.sensitivity)}`}>
                        {data.sensitivity} Security
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )

      case 'simple-permissions':
        return (
          <div className="space-y-6">
            <h3 className="text-2xl font-bold text-gray-900 mb-6">Simple Permission System</h3>
            
            <div className="bg-orange-50 border border-orange-200 rounded-lg p-6 mb-8">
              <div className="flex items-center mb-4">
                <Settings className="w-6 h-6 text-orange-600 mr-3" />
                <h4 className="text-lg font-semibold text-orange-900">Easy to Understand</h4>
              </div>
              <p className="text-orange-800">
                Our permission system uses clear language and visual indicators, making it easy for 
                community members to understand and control who has access to their information.
              </p>
            </div>

            <div className="space-y-6">
              <h5 className="text-lg font-semibold text-gray-900">Permission Levels</h5>
              {permissionLevels.map((level, index) => (
                <div key={index} className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
                  <h6 className="text-lg font-semibold text-gray-900 mb-4">{level.level}</h6>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                      <h7 className="font-medium text-green-700 mb-3 flex items-center">
                        <CheckCircle className="w-4 h-4 mr-2" />
                        What They Can Do
                      </h7>
                      <ul className="space-y-2">
                        {level.access.map((item, i) => (
                          <li key={i} className="text-sm text-gray-600 flex items-start">
                            <div className="w-2 h-2 bg-green-500 rounded-full mr-2 mt-2"></div>
                            {item}
                          </li>
                        ))}
                      </ul>
                    </div>
                    
                    <div>
                      <h7 className="font-medium text-red-700 mb-3 flex items-center">
                        <AlertTriangle className="w-4 h-4 mr-2" />
                        Restrictions
                      </h7>
                      <ul className="space-y-2">
                        {level.restrictions.map((item, i) => (
                          <li key={i} className="text-sm text-gray-600 flex items-start">
                            <div className="w-2 h-2 bg-red-500 rounded-full mr-2 mt-2"></div>
                            {item}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )

      default:
        return null
    }
  }

  return (
    <main className="min-h-screen bg-gray-50">
      <Header />
      
      <div className="container-max py-8">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">Data Protection & Privacy</h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Your community's data is protected by comprehensive security measures and community-controlled access policies
          </p>
        </div>

        {/* Feature Tabs */}
        <div className="flex flex-wrap justify-center gap-4 mb-8">
          {protectionFeatures.map((feature) => (
            <button
              key={feature.id}
              onClick={() => setActiveTab(feature.id)}
              className={`flex items-center px-6 py-3 rounded-lg font-medium transition-colors ${
                activeTab === feature.id
                  ? `${getColorClasses(feature.color)} border-2`
                  : 'bg-white text-gray-600 border-2 border-gray-200 hover:border-gray-300'
              }`}
            >
              <feature.icon className="w-5 h-5 mr-2" />
              {feature.title}
            </button>
          ))}
        </div>

        {/* Content */}
        <div className="bg-gray-50 rounded-2xl p-8">
          {renderContent()}
        </div>
      </div>

      <Footer />
    </main>
  )
}
